### ISSUE TITLE
Feature Request: Automatic EDF File Repair

### ISSUE THREAD

**Issue by fundamental** [Teuniz/EDFbrowser#19]
Both EDFbrowser and edflib are quite strict on what sort of error in the EDF file that they accept.
For some errors the header editor can allow for some minor fixes, however the fixes are pretty simple string substitutions there, so they should be something that can be automated.
Additionally refusing to accept channels where the physical or digital minimum and maximum are equal is logical, but making an entire file unusable isn't great.
edflib doesn't make it simple to change fields and deserializing and reserializing a file is painful to write out (I tried making the tool to fix a few minor field errors myself prior to this request, but it looks like there's some logical error in my code).

In particular the DREAMS database seems to have a number of ill formed EDF files which I would love to view in EDFbrowser, however the chan.min=chan.max problem prevents this from happening and I don't know of any external tool which is designed to make fixing this somewhat easy.
See: http://www.tcts.fpms.ac.be/~devuyst/Databases/DatabaseSpindles/ for some of the buggy files.

**Comment by raubsau** [comment]
I would like to additionally propose to automatically set the second crosshair to the "end" postion of an annotation (end = onset + duration).
That would allow to easily see the whole annotation event; right now there is only guessing where the annotation event might end.

Nonetheless - superb program, thank you!

**Comment by jusjusjus** [comment]
@raubsau, did you try my fork called edfView?  If you get it to compile, I have altered the annotation process a bit to make it quicker to work with.  It's a bit hacky but maybe a good prototype to make a big number of annotations.

**Comment by raubsau** [comment]
@jusjusjus, I did, and cannot get it to compile (Ubuntu 16.04, both Qt4 and Qt5). Thank you for your suggestion.

**Comment by jusjusjus** [comment]
Sure, it compiles on my ubntu 16.04.  Post an issue with error msg if you
want help.
