### ISSUE TITLE
unisens2EDF Bug with "xml_get_attribute_of_element()" function

### ISSUE THREAD

**Issue by mooneyj** [Teuniz/EDFbrowser#22]
I've tried to convert some unisens.xml files using the "Unisens to EDF+ converter".
The error printed is:
"
Processing file:
/home/john/EDF/Example_001/unisens.xml
Error, can not find attribute "timestampStart".
"

I've traced this to an if statement:

  if(xml_get_attribute_of_element(xml_hdl, "timestampStart", str, 255))
  {
    textEdit1->append("Error, can not find attribute \"timestampStart\".\n");
    return;
  }

It's not the other timestampStart conditional, which checks the sanity of the timestampStart str. The actual str passes the conditional.
So the bug is something to do with the function "xml_get_attribute_of_element()" or "xml_attribute()" which are in xml.cpp

I have no experience with xml and very little with cpp. So i need help!

**Comment by mooneyj** [comment]
Here is the example data I have tried:

http://www.unisens.org/downloads.php
&
http://www.movisens.com/wp-content/downloads/data_ekgmove_parcours.zip

**Comment by Teuniz** [comment]
Fixed. Pull and recompile.
Thanks for reporting.

**Comment by mooneyj** [comment]
I also confirm it works. Thanks!
