### ISSUE TITLE
'Stairs' graph at lower frequencies

### ISSUE THREAD

**Issue by eyalasko** [Teuniz/EDFbrowser#26]
Hi, 

Slow sampling rate (like this 10Hz EMG RMS: http://prntscr.com/9euqjz) is drawn as a series of steps.
Can it be drawn as a continuous  rather than steps (like screen caps shown on the website) ?

Thanks,
Eyal Lasko
eyal.lasko _at_ gmail.com

https://goo.gl/w420ef

http://prntscr.com/9euqjz
![image](https://cloud.githubusercontent.com/assets/4146353/11842733/27be36b8-a40e-11e5-99e3-f255c5516550.png)

**Comment by Teuniz** [comment]
Set the timescale to 2 minutes.
The only other option is to use a higher samplingrate during recording.

![edfbrowser](https://cloud.githubusercontent.com/assets/4106831/11850862/24ae3f00-a430-11e5-8b09-90e21392bed6.png)

**Comment by eyalasko** [comment]
Thank you very much for your prompt reply.  It is really appreciated! 

Can you direct me to the trace plotting module/function to try and tweak it slightly to my needs? 

Thanks again, 
Eyal

**Comment by Teuniz** [comment]
That part is in the file viewcurve.cpp.  There are two stages:
In the function drawCurve_stage_1() the raw samples are processed, scaled, downsampled and prepared for drawing. If threads are enabled, which is the default, it's done in the function run() instead, somewhere at line 3058:

<pre>
      if(s&gt;=signalcomp-&gt;sample_start)
      {
        x1 = (int)((double)s / signalcomp-&gt;sample_pixel_ratio);
        y1 = signalcomp-&gt;oldvalue;
        x2 = (int)(((double)s + 1.0) / signalcomp-&gt;sample_pixel_ratio);
        y2 = value;

        if(signalcomp-&gt;samples_on_screen &lt; (w / 2))
        {
          graphicBuf[*screensamples].graphicLine[i].x1 = x1 - signalcomp-&gt;pixels_shift;
          graphicBuf[*screensamples].graphicLine[i].y1 = y2;
          graphicBuf[*screensamples].graphicLine[i].x2 = x2 - signalcomp-&gt;pixels_shift;
          graphicBuf[*screensamples].graphicLine[i].y2 = y2;

          if(*screensamples)
          {
            (*screensamples)++;

            graphicBuf[*screensamples].graphicLine[i].x1 = x1 - signalcomp-&gt;pixels_shift;
            graphicBuf[*screensamples].graphicLine[i].y1 = y1;
            graphicBuf[*screensamples].graphicLine[i].x2 = x1 - signalcomp-&gt;pixels_shift;
            graphicBuf[*screensamples].graphicLine[i].y2 = y2;
          }

          (*screensamples)++;
        }
        else
        {
          if(!(*screensamples))
          {
            graphicBuf[*screensamples].graphicLine[i].x1 = x1;
            graphicBuf[*screensamples].graphicLine[i].y1 = y1;
            graphicBuf[*screensamples].graphicLine[i].x2 = x2;
            graphicBuf[*screensamples].graphicLine[i].y2 = y2;

            (*screensamples)++;
          }
          else
          {
            if((x1==x2)&amp;&amp;(x1==graphicBuf[(*screensamples)-1].graphicLine[i].x1)&amp;&amp;
              (graphicBuf[(*screensamples)-1].graphicLine[i].x1==graphicBuf[(*screensamples)-1].graphicLine[i].x2))
            {
              maximum = y1;
              if(y2&gt;maximum)  maximum = y2;
              if(graphicBuf[(*screensamples)-1].graphicLine[i].y1&gt;maximum)  maximum = graphicBuf[(*screensamples)-1].graphicLine[i].y1;
              if(graphicBuf[(*screensamples)-1].graphicLine[i].y2&gt;maximum)  maximum = graphicBuf[(*screensamples)-1].graphicLine[i].y2;

              minimum = y1;
              if(y2&lt;minimum)  minimum = y2;
              if(graphicBuf[(*screensamples)-1].graphicLine[i].y1&lt;minimum)  minimum = graphicBuf[(*screensamples)-1].graphicLine[i].y1;
              if(graphicBuf[(*screensamples)-1].graphicLine[i].y2&lt;minimum)  minimum = graphicBuf[(*screensamples)-1].graphicLine[i].y2;

              graphicBuf[(*screensamples)-1].graphicLine[i].y1 = maximum;
              graphicBuf[(*screensamples)-1].graphicLine[i].y2 = minimum;
            }
            else
            {
              graphicBuf[*screensamples].graphicLine[i].x1 = x1;
              graphicBuf[*screensamples].graphicLine[i].y1 = y1;
              graphicBuf[*screensamples].graphicLine[i].x2 = x2;
              graphicBuf[*screensamples].graphicLine[i].y2 = y2;

              if((*screensamples)&lt;(w * 2))  (*screensamples)++;
            }
          }
        }
      }
</pre>

The drawing itself is done in the function drawCurve_stage_2() somewhere at line 1926:
<pre>
    for(j=0; j&lt;screensamples[i]; j++)
    {
      painter->drawLine(graphicBuf[j].graphicLine[i].x1,
                        graphicBuf[j].graphicLine[i].y1,
                        graphicBuf[j].graphicLine[i].x2,
                        graphicBuf[j].graphicLine[i].y2);
    }
</pre>

Have fun.

**Comment by Teuniz** [comment]
Closed because the issue has been resolved.
It's possible to select linear interpolation in the settings menu.
