### ISSUE TITLE
Visualization of time-series data

### ISSUE THREAD

**Issue by breznak** [Teuniz/EDFbrowser#27]
Hello, 
we are developing https://github.com/nupic-community/nupic.visualizations , an interactive time-series data graph tool and anomaly hihglighting, I'm wondering if such functionality would be of interest for your project? 
Cheers,

**Comment by Teuniz** [comment]
Compliments for your project. It looks very nice.
I was thinking the opposite. Why don't you adopt the EDF format into your project?
With this library it's peanuts to implement:
https://github.com/Teuniz/EDFlib

**Comment by breznak** [comment]
Hi @Teuniz , 
thanks for your feedback! The `EDF+` format looks indeed interesting for us. Problems I see are with difficulty to parse (if written from scratch by us; by chance, a javascript parser for EDF+ probably doesn't exist, right? My quick search didn't find any mentions), or portability (if using `EDFlib` of yours, as our project fancies the ease of installation - the only requirement is JS-enabled browser). 

So I see 2 solutions: 
* rewrite custom EDF+ parser in JS
 - complicated
* use EDFlib
 - to convert files to CSV
 - easier
 - needs parser compiled for all platforms

For start, I seem to prefer the latter. Could you please show me an example of EDFlib call that would open a generic EDF+ file and write its contents as CSV?

**Comment by Teuniz** [comment]
Scroll down on the EDFlib webpage. There's something about a Java wrapper.
Maybe you can use that?
