### ISSUE TITLE
how to generate edfbrowser.exe static link with qt?

### ISSUE THREAD

**Issue by chptx** [Teuniz/EDFbrowser#29]
edfbrowser.exe extract from http://www.teuniz.net/edfbrowser/setup_edfbrowser_158.zip can run standalone, but same file build from source can't, and it say missing `libgcc_s_dw2-1.dll`、qtcore ... etc.

**Comment by Teuniz** [comment]
The Qt libraries are shared objects (dll's on windows). You can't use them to compile a static version.
You have to configure Qt for static linking and then you have to recompile the Qt libraries from source.
After that you can compile EDFbrowser static.
