### ISSUE TITLE
Annotation Duration Display

### ISSUE THREAD

**Issue by bostal** [Teuniz/EDFbrowser#32]
Hi!
This is a great program. Sorry if it's already a feature and I missed it. But is it possible to visually display the duration of annotations? The only way I can see this information is in the 'annotation editor' box. 
Kind regards,
bostal

**Comment by Teuniz** [comment]
You are right. The only way to see the duration of an annotation is to keep the mouse cursor still
above an annotation in the annotationlist.
I could add a column in the annotation list for the duration and/or put an overlay in the signal viewer.
I'll put it on the wishlist.

**Comment by bostal** [comment]
Thanks for replying to my comment. An overlay on the visual signal viewer would really be enormously useful.
Kind regards.
bostal

**Comment by raubsau** [comment]
(This text was posted in the wrong issue:) 

I would like to additionally propose to automatically set the second crosshair to the "end" postion of an annotation (end = onset + duration).
That would allow to easily see the whole annotation event; right now there is only guessing where the annotation event might end.

Nonetheless - superb program, thank you!

**Comment by Teuniz** [comment]
I created an overlay for the background color for the duration of an annotation.
I still need to make it possible to configure the color and alphablending in the settings menu.
Please pull & recompile and try.

**Comment by raubsau** [comment]
@Teuniz Excellent, works as expected on my Linux machine.

**Comment by Teuniz** [comment]
I added the possibility to select the color and alpha blending for the background color of the duration in the settings menu.

**Comment by Teuniz** [comment]
Closed because the issue has been resolved with version 1.60 (released now).
