### ISSUE TITLE
Export of Annotations: Duration of -1,0 second is not exported

### ISSUE THREAD

**Issue by raubsau** [Teuniz/EDFbrowser#39]
Using both current Windows Build and current Linux compilation,

when creating a new annotations with length of -1 second, the exported annotations file does not contain any value/character in the duration column.

If it is of any importance, Duration in the Annotation editor pane is shown as -1,000 sec, mind the comma.

**Comment by Teuniz** [comment]
That's exactly what it should do. If a duration is unknown or not applicable, you set it to -1 to tell EDFbrowser that it should write nothing in the duration column because there's no duration.

**Comment by raubsau** [comment]
Ok, noted.

When I try to import the exported annotations file (EDFbrowser freshly started and EDF file opened) noting happens - "Import Done", but no annotations show up in the Annotations or annotation editor pane. Import settings match export settings in regard to columns, timestamp format and data start line.

**Comment by Teuniz** [comment]
After a short investigation it looks like that the annotations importer doesn't deal well with empty columns.
I'll look into it and report back here when I have some news.

**Comment by Teuniz** [comment]
I made some changes in the annotations importer. It should work correctly now.
You can pull the source and recompile to try. Let me know the result.

**Comment by raubsau** [comment]
This solved the issue, thank you very much.
Could you kindly provide an updated version for Windows users as well?

**Comment by Teuniz** [comment]
The new version 1.63 is available.
